version: "3.8"
services:

    db:
        image: mariadb/server
        container_name: db_docker_usermanag
        restart: always
        volumes:
            - ./.docker/datas/mysql:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        networks:
            - dev

    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin_docker_usermanag
        restart: always
        depends_on:
            - db
        ports:
            - 8080:80
        environment:
            PMA_HOST: db
        networks:
            - dev

    php:
        build: ./.docker/php
        container_name: www_docker_usermanag
        ports:
          - "8000:80"
        volumes:
            - ./.docker/php/vhosts:/etc/apache2/sites-enabled
            - ../:/var/www
        restart: always
        networks:
            - dev
networks:
    dev: